### ISSUE TITLE
Docker compose file

### ISSUE THREAD

**Issue by mgscreativa** [magna-z/docker-traccar#9]
Hi! I'm trying to use this with docker compose. Do you have any sample to start out? I want to use your Traccar container with HTTPS in my own Ubuntu server with ISPConfig/Let'sEncrypt.

Thanks!

**Comment by mgscreativa** [comment]
Got it working with this docker.compose.yml file

```
version: '2'
services:
    web:
        image: 'magnaz/traccar:debian'
        restart: always
        hostname: 'track.xxxxxxxx.com'
        container_name: traccar
        ports:
            - '280:8082'
            - '5000-5150:5000-5150'
            - '5000-5150:5000-5150/udp'
        volumes:
            - '/etc/timezone:/etc/timezone:ro'
            - '/etc/localtime:/etc/localtime:ro'
            - '/media/data/traccar/logs:/opt/traccar/logs:rw'
            - '/media/data/traccar/conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro'
```
To start it `docker-compose up -d`

Do you know how can I setup this to use HTTPS? I'm currently using ISPConfig with Lets'Encrypt enabled and the site works just fine, but enabling HTTPS proxy to docker image fails.

I'm using this apache proxy conf:
```
<Proxy *>
    Allow from localhost
</Proxy>

ProxyPreserveHost On
SSLProxyEngine On
RequestHeader set Front-End-Https "On"

ProxyPass /api/socket wss://lucas.mgscreativa.com.ar:280/api/socket
ProxyPassReverse /api/socket wss://lucas.mgscreativa.com.ar:280/api/socket

ProxyPass / https://lucas.mgscreativa.com.ar:280/
ProxyPassReverse / https://lucas.mgscreativa.com.ar:280/
```
